package com.example.ui

import android.content.Context
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.staticCompositionLocalOf
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.util.Locale

enum class AppLanguage(val code: String, val title: String, val nativeTitle: String) {
    ENGLISH("en", "English", "English"),
    RUSSIAN("ru", "Russian", "Русский");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return if (code.startsWith("ru", ignoreCase = true)) RUSSIAN else ENGLISH
        }
    }
}

data class AppStrings(
    val appName: String,
    val savedMessages: String,
    val savedMessagesDesc: String,
    val welcomeSavedMessages: String,
    val searchMessages: String,
    val pinChat: String,
    val unpinChat: String,
    val muteNotifications: String,
    val markAsUnread: String,
    val archive: String,
    val deleteChat: String,
    val newChat: String,
    val recipientName: String,
    val create: String,
    val selectChatPrompt: String,
    val online: String,
    val offline: String,
    val typing: String,
    val messagePlaceholder: String,
    val holdToRecord: String,
    val recording: String,
    val slideToCancel: String,
    val photo: String,
    val video: String,
    val voiceMessage: String,
    val reply: String,
    val copy: String,
    val forward: String,
    val edit: String,
    val delete: String,
    val retry: String,
    val failedToSend: String,
    val settings: String,
    val account: String,
    val profile: String,
    val editProfile: String,
    val name: String,
    val username: String,
    val phone: String,
    val save: String,
    val cancel: String,
    val ok: String,
    val privacySecurity: String,
    val notifications: String,
    val app: String,
    val appearance: String,
    val language: String,
    val selectLanguage: String,
    val english: String,
    val russian: String,
    val storageData: String,
    val support: String,
    val helpCenter: String,
    val reportProblem: String,
    val contactSupport: String,
    val about: String,
    val privacyPolicy: String,
    val termsService: String,
    val comingSoon: String,
    val featureNotImplemented: String,
    val tapAvatarToChoose: String,
    val aboutDescription: String,
    val version: String,
    val developer: String,
    val leadDeveloper: String,
    val copyright: String,
    val justNow: String,
    val today: String,
    val yesterday: String,
    val permissionRequired: String,
    val camera: String,
    val gallery: String,
    val logout: String,
    val deleteAccount: String,
    val logoutConfirm: String,
    val deleteAccountConfirm: String,
    // Auth & Guest Mode Strings
    val authTitle: String,
    val authSubtitle: String,
    val phoneNumber: String,
    val sendCode: String,
    val orDivider: String,
    val continueAsGuest: String,
    val guestModeSubtitle: String,
    val virtualNumberLabel: String,
    val guestVirtualNumberAssigned: String,
    val guestBadge: String,
    val phoneAccountBadge: String,
    val accountTypeLabel: String,
    val selectCountry: String,
    val searchCountry: String,
    val enterCode: String,
    val verifyCode: String,
    val codeExpired: String,
    val invalidCode: String,
    val chooseUsername: String,
    val startMessaging: String,
    val usernameTooShort: String,
    val usernameInvalidChars: String,
    val usernameAlreadyTaken: String,
    val guestNotice: String,
    val callUnavailableSelf: String,
    val callUnavailableAi: String,
    // HexShard Final Auth Architecture strings
    val signUpTab: String,
    val signInTab: String,
    val passwordLabel: String,
    val passwordPlaceholder: String,
    val passwordConfirmLabel: String,
    val passwordMismatch: String,
    val passwordTooShort: String,
    val telegramVerificationNotice: String,
    val telegramBotButton: String,
    val telegramEnterCodePrompt: String,
    val telegramCodePlaceholder: String,
    val verifyTelegramCode: String,
    val skipTelegramForNow: String,
    val privateVirtualNumberTitle: String,
    val privateVirtualNumberDesc: String,
    val privateNumberCopied: String,
    val virtualNumberWarning: String,
    val copyNumber: String,
    val continueToApp: String,
    val invalidCredentials: String,
    val accountNotFound: String,
    val privateIdentityTitle: String,
    val privateIdentityDesc: String,
    val generateNumber: String,
    val useThisNumber: String,
    val accountIdLabel: String,
    val accountIdDescription: String,
    val copyAccountId: String,
    val accountIdCopied: String,
    val telegramConnected: String,
    val telegramNotConnected: String,
    val connectTelegram: String,
    val accountReadyTitle: String,
    val accountReadyDesc: String,
    val enterHexShard: String,
    val connectionError: String,
    val privateNumberLabel: String,
    val skipPrivateNumber: String,
    val notAssigned: String,
    val telegramBindingTitle: String,
    val telegramBindingDesc: String,
    val simulateBotCode: String,
    val aiRateLimited: String,
    val aiUnauthorized: String,
    val aiUnavailable: String,
    val aiQuotaExceeded: String,
    val aiInvalidRequest: String,
    val aiNetworkError: String,
    val aiFunctionNotFound: String,
    val aiDeploymentUnavailable: String,
    val aiModelUnavailable: String,
    val aiConfigurationError: String,
    val noConversationsYet: String,
    val welcomeHexShard: String,
    val welcomeHexShardDesc: String,
    val initialsMandatory: String,
    val initialsLabel: String,
    val resultsCount: String,
    val micPermissionRequired: String,
    val ventaxisDesc: String,
    val hexagonDesc: String,
    val noMessagesFound: String,
    val sayHiTo: String
)

val EnglishStrings = AppStrings(
    appName = "HexShard",
    savedMessages = "Saved Messages",
    savedMessagesDesc = "Store notes, save messages, and keep media here.",
    welcomeSavedMessages = "Welcome to Saved Messages!",
    searchMessages = "Search messages...",
    pinChat = "Pin Chat",
    unpinChat = "Unpin Chat",
    muteNotifications = "Mute Notifications",
    markAsUnread = "Mark as Unread",
    archive = "Archive",
    deleteChat = "Delete Chat",
    newChat = "New Chat",
    recipientName = "Recipient Name",
    create = "Create",
    selectChatPrompt = "Select a chat to start messaging",
    online = "online",
    offline = "offline",
    typing = "typing...",
    messagePlaceholder = "Message",
    holdToRecord = "Hold to record, release to send",
    recording = "Recording...",
    slideToCancel = "Slide left to cancel",
    photo = "Photo",
    video = "Video",
    voiceMessage = "Voice message",
    reply = "Reply",
    copy = "Copy",
    forward = "Forward",
    edit = "Edit",
    delete = "Delete",
    retry = "Retry",
    failedToSend = "Failed to send",
    settings = "Settings",
    account = "Account",
    profile = "Profile",
    editProfile = "Edit Profile",
    name = "Name",
    username = "Username",
    phone = "Phone",
    save = "Save",
    cancel = "Cancel",
    ok = "OK",
    privacySecurity = "Privacy & Security",
    notifications = "Notifications",
    app = "App",
    appearance = "Appearance",
    language = "Language",
    selectLanguage = "Select Language",
    english = "English",
    russian = "Russian",
    storageData = "Data & Storage",
    support = "Support",
    helpCenter = "Help Center / FAQ",
    reportProblem = "Report a Problem",
    contactSupport = "Contact Support",
    about = "About",
    privacyPolicy = "Privacy Policy",
    termsService = "Terms of Service",
    comingSoon = "Coming Soon",
    featureNotImplemented = "This feature is not yet implemented.",
    tapAvatarToChoose = "Tap avatar to choose photo",
    aboutDescription = "HexShard is a private, minimalist messenger designed for secure communication with end-to-end encryption.",
    version = "Version 1.0.0",
    developer = "Developer: Ventaxis Corp",
    leadDeveloper = "Lead Developer: Jenk Jenkich",
    copyright = "© 2026 Ventaxis Corp. All rights reserved.",
    justNow = "Just now",
    today = "Today",
    yesterday = "Yesterday",
    permissionRequired = "Permission required",
    camera = "Camera",
    gallery = "Gallery",
    logout = "Log Out",
    deleteAccount = "Delete Account",
    logoutConfirm = "Are you sure you want to log out? Local cryptographic keys will remain on your device, but session access will require re-authentication.",
    deleteAccountConfirm = "Are you sure you want to delete your account? This action permanently removes your public identity, unlinks your phone, and wipes your local encrypted message history.",
    // Auth & Guest Mode
    authTitle = "HexShard",
    authSubtitle = "Privacy by design.",
    phoneNumber = "Phone Number",
    sendCode = "Send Code",
    orDivider = "OR",
    continueAsGuest = "Continue as Guest",
    guestModeSubtitle = "Try HexShard with a virtual ID without sharing your real phone number.",
    virtualNumberLabel = "Virtual Number",
    guestVirtualNumberAssigned = "Virtual ID assigned for guest session",
    guestBadge = "Guest Account",
    phoneAccountBadge = "Verified Account",
    accountTypeLabel = "Account Type",
    selectCountry = "Select Country",
    searchCountry = "Search country or dial code...",
    enterCode = "Enter Verification Code",
    verifyCode = "Verify",
    codeExpired = "Verification code expired. Request a new code.",
    invalidCode = "Invalid code. Please check and try again.",
    chooseUsername = "Choose Username",
    startMessaging = "Start Messaging",
    usernameTooShort = "Username must be 3-30 characters",
    usernameInvalidChars = "Username can only contain letters, numbers, and underscores",
    usernameAlreadyTaken = "Username is already taken. Please choose another.",
    guestNotice = "HexShard operates with end-to-end encryption. Your private number is a cryptographic internal identifier, not a public cellular telephone line.",
    callUnavailableSelf = "Calls to Saved Messages are not available",
    callUnavailableAi = "HexShard AI does not support voice or video calls",
    signUpTab = "Create Account",
    signInTab = "Sign In",
    passwordLabel = "Password",
    passwordPlaceholder = "Enter password",
    passwordConfirmLabel = "Confirm Password",
    passwordMismatch = "Passwords do not match",
    passwordTooShort = "Password must be at least 6 characters",
    telegramVerificationNotice = "Protect your account with Telegram 2FA verification code.",
    telegramBotButton = "Open @HexShardBot",
    telegramEnterCodePrompt = "Enter the 6-digit code received from the bot",
    telegramCodePlaceholder = "Verification Code",
    verifyTelegramCode = "Confirm Code",
    skipTelegramForNow = "Skip for now",
    privateVirtualNumberTitle = "Your Private Virtual Number",
    privateVirtualNumberDesc = "This internal HexShard number protects your real identity. Use it to share contact without revealing cellular information.",
    privateNumberCopied = "Private number copied to clipboard",
    virtualNumberWarning = "Fictional internal HexShard prefix (+999). It does not receive cellular SMS or public telephony.",
    copyNumber = "Copy Number",
    continueToApp = "Continue to HexShard",
    invalidCredentials = "Invalid username or password",
    accountNotFound = "Account not found",
    privateIdentityTitle = "Your Private Identity",
    privateIdentityDesc = "Choose or customize an 8-digit private virtual number under the +999 prefix.",
    generateNumber = "Generate",
    useThisNumber = "Use this number",
    accountIdLabel = "Account ID",
    accountIdDescription = "Server-side identifier used for security & @HexShardBot verification.",
    copyAccountId = "Copy Account ID",
    accountIdCopied = "Account ID copied to clipboard",
    telegramConnected = "Verified via Telegram",
    telegramNotConnected = "Not connected",
    connectTelegram = "Connect @HexShardBot",
    accountReadyTitle = "Account Ready",
    accountReadyDesc = "Your cryptographic identity and keys have been initialized.",
    enterHexShard = "Enter HexShard",
    connectionError = "Connection unavailable. Please check your internet connection and try again.",
    privateNumberLabel = "Private Number",
    skipPrivateNumber = "Skip private number",
    notAssigned = "Not assigned",
    telegramBindingTitle = "Telegram Account Binding",
    telegramBindingDesc = "Send your Account ID to @HexShardBot. The bot will bind to your account and send your verification code.",
    simulateBotCode = "Paste bot verification code",
    aiRateLimited = "Too many requests to AI. Please wait %d sec.",
    aiUnauthorized = "Sign in to chat with the AI assistant.",
    aiUnavailable = "AI service is temporarily unavailable. Please try again later.",
    aiQuotaExceeded = "AI request limit exceeded.",
    aiInvalidRequest = "Invalid AI request.",
    aiNetworkError = "Network error connecting to AI. Please check your internet connection.",
    aiFunctionNotFound = "AI service endpoint not found (404). Please ensure the Edge Function is deployed.",
    aiDeploymentUnavailable = "AI service deployment is currently unavailable.",
    aiModelUnavailable = "The requested AI model is unavailable on the server.",
    aiConfigurationError = "AI server configuration error. API key or service missing.",
    noConversationsYet = "No conversations yet. Tap + to start.",
    welcomeHexShard = "Welcome to HexShard Messenger",
    welcomeHexShardDesc = "Select an encrypted thread on the left pane under your radar to begin exchanging shards of ideas.",
    initialsMandatory = "Both name and initials are mandatory!",
    initialsLabel = "Initials (e.g., JD)",
    resultsCount = "%d results",
    micPermissionRequired = "Microphone permission required",
    ventaxisDesc = "Ventaxis AI • Smart assistant",
    hexagonDesc = "Hexagon AI (Beta) • Experimental engine",
    noMessagesFound = "No messages found for '%s'",
    sayHiTo = "Say hi to %s!"
)

val RussianStrings = AppStrings(
    appName = "HexShard",
    savedMessages = "Избранное",
    savedMessagesDesc = "Сохраняйте важные заметки, файлы и сообщения здесь.",
    welcomeSavedMessages = "Добро пожаловать в Избранное!",
    searchMessages = "Поиск сообщений...",
    pinChat = "Закрепить чат",
    unpinChat = "Открепить чат",
    muteNotifications = "Отключить уведомления",
    markAsUnread = "Пометить непрочитанным",
    archive = "В архив",
    deleteChat = "Удалить чат",
    newChat = "Новый чат",
    recipientName = "Имя собеседника",
    create = "Создать",
    selectChatPrompt = "Выберите чат для начала общения",
    online = "в сети",
    offline = "не в сети",
    typing = "печатает...",
    messagePlaceholder = "Сообщение",
    holdToRecord = "Удерживайте для записи, отпустите для отправки",
    recording = "Запись...",
    slideToCancel = "Смахните влево для отмены",
    photo = "Фото",
    video = "Видео",
    voiceMessage = "Голосовое сообщение",
    reply = "Ответить",
    copy = "Копировать",
    forward = "Переслать",
    edit = "Изменить",
    delete = "Удалить",
    retry = "Повторить",
    failedToSend = "Не удалось отправить",
    settings = "Настройки",
    account = "Аккаунт",
    profile = "Профиль",
    editProfile = "Изменить профиль",
    name = "Имя",
    username = "Имя пользователя",
    phone = "Телефон",
    save = "Сохранить",
    cancel = "Отмена",
    ok = "ОК",
    privacySecurity = "Конфиденциальность",
    notifications = "Уведомления",
    app = "Приложение",
    appearance = "Оформление",
    language = "Язык",
    selectLanguage = "Выберите язык",
    english = "English",
    russian = "Русский",
    storageData = "Данные и память",
    support = "Поддержка",
    helpCenter = "Помощь / FAQ",
    reportProblem = "Сообщить о проблеме",
    contactSupport = "Связаться с поддержкой",
    about = "О приложении",
    privacyPolicy = "Политика конфиденциальности",
    termsService = "Условия использования",
    comingSoon = "Скоро появится",
    featureNotImplemented = "Эта функция еще не реализована.",
    tapAvatarToChoose = "Нажмите на аватар для выбора фото",
    aboutDescription = "HexShard — быстрый и приватный мессенджер для безопасного общения со сквозным шифрованием.",
    version = "Версия 1.0.0",
    developer = "Разработчик: Ventaxis Corp",
    leadDeveloper = "Ведущий разработчик: Jenk Jenkich",
    copyright = "© 2026 Ventaxis Corp. Все права защищены.",
    justNow = "Только что",
    today = "Сегодня",
    yesterday = "Вчера",
    permissionRequired = "Требуется разрешение",
    camera = "Камера",
    gallery = "Галерея",
    logout = "Выйти из аккаунта",
    deleteAccount = "Удалить аккаунт",
    logoutConfirm = "Вы уверены, что хотите выйти? Локальные ключи сохранятся на устройстве, но для доступа к сессии потребуется повторный вход.",
    deleteAccountConfirm = "Вы уверены, что хотите удалить аккаунт? Это действие безвозвратно удалит ваш публичный профиль, отвяжет номер телефона и сотрет зашифрованную историю сообщений.",
    // Auth & Guest Mode
    authTitle = "HexShard",
    authSubtitle = "Приватность по умолчанию.",
    phoneNumber = "Номер телефона",
    sendCode = "Получить код",
    orDivider = "ИЛИ",
    continueAsGuest = "Войти как гость",
    guestModeSubtitle = "Попробуйте HexShard с виртуальным ID без ввода настоящего номера телефона.",
    virtualNumberLabel = "Виртуальный номер",
    guestVirtualNumberAssigned = "Виртуальный ID назначен для гостевой сессии",
    guestBadge = "Гостевой аккаунт",
    phoneAccountBadge = "Подтвержденный аккаунт",
    accountTypeLabel = "Тип аккаунта",
    selectCountry = "Выберите страну",
    searchCountry = "Поиск страны или кода...",
    enterCode = "Введите код из SMS",
    verifyCode = "Подтвердить",
    codeExpired = "Срок действия кода истек. Запросите новый код.",
    invalidCode = "Неверный код. Проверьте и попробуйте снова.",
    chooseUsername = "Выберите имя пользователя",
    startMessaging = "Начать общение",
    usernameTooShort = "Имя пользователя должно быть от 3 до 30 символов",
    usernameInvalidChars = "Имя пользователя может содержать только латинские буквы, цифры и _",
    usernameAlreadyTaken = "Это имя пользователя уже занято. Выберите другое.",
    guestNotice = "HexShard работает с полным сквозным шифрованием (E2EE). Ваш приватный номер является внутренним криптографическим идентификатором и не является реальным номером мобильного телефона.",
    callUnavailableSelf = "Звонки в Избранное недоступны",
    callUnavailableAi = "HexShard AI не поддерживает голосовые и видеозвонки",
    signUpTab = "Регистрация",
    signInTab = "Вход",
    passwordLabel = "Пароль",
    passwordPlaceholder = "Введите пароль",
    passwordConfirmLabel = "Подтверждение пароля",
    passwordMismatch = "Пароли не совпадают",
    passwordTooShort = "Пароль должен быть не менее 6 символов",
    telegramVerificationNotice = "Защитите ваш аккаунт с помощью кода подтверждения через Telegram 2FA.",
    telegramBotButton = "Открыть @HexShardBot",
    telegramEnterCodePrompt = "Введите 6-значный код, полученный от бота",
    telegramCodePlaceholder = "Код подтверждения",
    verifyTelegramCode = "Подтвердить код",
    skipTelegramForNow = "Пропустить пока",
    privateVirtualNumberTitle = "Ваш приватный номер",
    privateVirtualNumberDesc = "Этот внутренний номер HexShard защищает ваш реальный номер. Делитесь им для связи без раскрытия персональных данных.",
    privateNumberCopied = "Приватный номер скопирован в буфер",
    virtualNumberWarning = "Внутренний префикс HexShard (+999). Не принимает мобильные SMS и сотовые вызовы.",
    copyNumber = "Скопировать номер",
    continueToApp = "Перейти в HexShard",
    invalidCredentials = "Неверное имя пользователя или пароль",
    accountNotFound = "Аккаунт не найден",
    privateIdentityTitle = "Ваша приватная идентичность",
    privateIdentityDesc = "Выберите или настройте 8-значный приватный виртуальный номер под префиксом +999.",
    generateNumber = "Сгенерировать",
    useThisNumber = "Использовать этот номер",
    accountIdLabel = "ID аккаунта",
    accountIdDescription = "Серверный идентификатор, используемый для безопасности и привязки к @HexShardBot.",
    copyAccountId = "Скопировать ID аккаунта",
    accountIdCopied = "ID аккаунта скопирован в буфер",
    telegramConnected = "Подтверждено через Telegram",
    telegramNotConnected = "Не привязан",
    connectTelegram = "Подключить @HexShardBot",
    accountReadyTitle = "Аккаунт готов",
    accountReadyDesc = "Ваша криптографическая идентичность и ключи успешно инициализированы.",
    enterHexShard = "Войти в HexShard",
    connectionError = "Подключение недоступно. Проверьте интернет-соединение и попробуйте снова.",
    privateNumberLabel = "Приватный номер",
    skipPrivateNumber = "Пропустить выбор номера",
    notAssigned = "Не назначен",
    telegramBindingTitle = "Привязка через Telegram",
    telegramBindingDesc = "Отправьте ваш ID боту @HexShardBot. Бот привяжется к вашему аккаунту и пришлет код подтверждения.",
    simulateBotCode = "Вставить проверочный код",
    aiRateLimited = "Слишком частые запросы к AI. Пожалуйста, подождите %d сек.",
    aiUnauthorized = "Для общения с AI необходимо войти в аккаунт.",
    aiUnavailable = "Сервис AI временно недоступен. Пожалуйста, попробуйте позже.",
    aiQuotaExceeded = "Превышен лимит запросов к AI ассистенту.",
    aiInvalidRequest = "Некорректный запрос к AI.",
    aiNetworkError = "Ошибка сети при обращении к AI. Проверьте интернет-соединение.",
    aiFunctionNotFound = "Эндпоинт AI не найден (404). Проверьте деплой Edge Function.",
    aiDeploymentUnavailable = "AI сервис временно недоступен.",
    aiModelUnavailable = "Запрошенная модель AI недоступна на сервере.",
    aiConfigurationError = "Ошибка конфигурации AI на сервере. Отсутствует ключ API.",
    noConversationsYet = "Нет диалогов. Нажмите + чтобы начать.",
    welcomeHexShard = "Добро пожаловать в HexShard Messenger",
    welcomeHexShardDesc = "Выберите зашифрованный чат слева, чтобы начать общение.",
    initialsMandatory = "Имя и инициалы обязательны!",
    initialsLabel = "Инициалы (напр. ИИ)",
    resultsCount = "Результатов: %d",
    micPermissionRequired = "Требуется разрешение на запись звука",
    ventaxisDesc = "Ventaxis AI • Умный ассистент",
    hexagonDesc = "Hexagon AI (Beta) • Экспериментальный движок",
    noMessagesFound = "Сообщения по запросу «%s» не найдены",
    sayHiTo = "Напишите первое сообщение для %s!"
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
val LocalAppLanguage = compositionLocalOf { AppLanguage.ENGLISH }

object LocalizationManager {
    private const val PREFS_NAME = "hexshard_profile"
    private const val KEY_LANGUAGE = "app_language"

    private val _currentLanguage = MutableStateFlow(AppLanguage.ENGLISH)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    fun init(context: Context) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        // Default is English as requested ("сначала английский, а потом на русский")
        val savedLang = prefs.getString(KEY_LANGUAGE, "en") ?: "en"
        val lang = AppLanguage.fromCode(savedLang)
        _currentLanguage.value = lang
        applyLocaleToConfiguration(context, lang)
    }

    fun setLanguage(context: Context, language: AppLanguage) {
        _currentLanguage.value = language
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_LANGUAGE, language.code).apply()
        applyLocaleToConfiguration(context, language)
    }

    fun getStrings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.ENGLISH -> EnglishStrings
            AppLanguage.RUSSIAN -> RussianStrings
        }
    }

    private fun applyLocaleToConfiguration(context: Context, language: AppLanguage) {
        try {
            val locale = Locale(language.code)
            Locale.setDefault(locale)
            val config = context.resources.configuration
            config.setLocale(locale)
            @Suppress("DEPRECATION")
            context.resources.updateConfiguration(config, context.resources.displayMetrics)
        } catch (e: Exception) {
            // Safe fallback
        }
    }
}
